server:
  port: 8081

spring:
  application:
    name: nacos-config-demo
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
        refresh-enabled: true
      discovery:
        group: DEFAULT_GROUP
        fail-fast: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
