-- 在 Mac 本地 FREEPDB1 上用 system 执行一次。
-- 不要使用内网生产密码。本地开发账号即可。

CREATE USER sprcp IDENTIFIED BY SprcpDev123
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO sprcp;
