server:
  port: 8083

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      discovery:
        group: DEFAULT_GROUP
        fail-fast: false

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
